### ISSUE TITLE
raspipool

### ISSUE THREAD

**Issue by segalion** [stritti/smart-swimming-pool#8]
Hello. I have been you are collecting related DIY automation swimming pool projects. Please, could you add this https://github.com/segalion/raspipool/ ?

and (wip) very visual wiki in https://github.com/segalion/raspipool/wiki

Thanks.

**Comment by stritti** [comment]
Shure. You are welcome to comment to. I added your project.

I really interested in your learnings to measure pH and ORB forms winter project extension.

**Comment by segalion** [comment]
Thanks for your reference.
This wintter will be my first so probably I can debut it more.
